import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'link',
      label: '💙 Discord Support',
      href: 'https://dsc.gg/inventutor',
    },
    {
      type: 'category',
      label: '📙 Docs',
      items: [
        'docs/index',
        'docs/official-links-and-staff-list',
        'docs/about-inventutor-pro',
        'docs/useful-tools',
        {
          type: 'category',
          label: 'Legal',
          items: [
            'docs/legal/affiliation-disclaimer',
            'docs/legal/branding-guidelines',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🎬 Tutorials',
      items: [
        {type: 'autogenerated', dirName: 'tutorials'},
      ],
    },
    {
      type: 'category',
      label: '🧩 Plugins',
      items: [
        {type: 'autogenerated', dirName: 'plugins'},
      ],
    },
    {
      type: 'category',
      label: '⚡ Components',
      items: [
        {type: 'autogenerated', dirName: 'components'},
      ],
    },
  ],
};

export default sidebars;
